# Ansible Inventory for Windows Servers
all:
  children:
    windows:
      hosts:
        # Replace with your actual Windows servers
        windows-server-01:
          ansible_host: 192.168.1.100
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_port: 5985
          ansible_winrm_server_cert_validation: ignore
        
        windows-server-02:
          ansible_host: 192.168.1.101
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_port: 5985
          ansible_winrm_server_cert_validation: ignore
      
      vars:
        # Common Windows connection settings
        ansible_user: Administrator
        ansible_password: "{{ vault_windows_password }}"
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_scheme: http
        ansible_port: 5985
        ansible_shell_type: powershell